#!/bin/bash

jar=panopticon.sa-1.0-SNAPSHOT-standalone-distro.jar
dir=$(dirname $0)
if [[ -f $jar ]] ; then
	root=$dir
else
	root=$dir/../target
fi	


set -x
JAVA_OPTS="\
	-Dlogback.configurationFile=panopticon-logback.xml"
	

if [[ "$@" == *--trace* ]] ; then
	JAVA_OPTS="$JAVA_OPTS -Ddebug.level=DEBUG"
	JAVA_OPTS="$JAVA_OPTS -Dtrace.level=DEBUG"
elif [[ "$@" == *--debug* ]] ; then
	JAVA_OPTS="$JAVA_OPTS -Ddebug.level=DEBUG"
fi
	
java $JAVA_OPTS -cp $root/$jar:$dir org.scriptbox.panopticon.main.MonitorCli "$@"
