#!/bin/bash

jar=panopticon-1.0-SNAPSHOT-standalone.jar
dir=$(dirname $0)
if [[ -f $jar ]] ; then
	root=$dir
else
	root=$dir/../build/distributions
fi	


set -x
JAVA_OPTS="\
	-Dlogback.configurationFile=panopticon-logback.xml"
	

if [[ "$@" == *--trace* ]] ; then
	JAVA_OPTS="$JAVA_OPTS -Ddebug.level=DEBUG"
	JAVA_OPTS="$JAVA_OPTS -Dtrace.level=DEBUG"
	# JAVA_OPTS="$JAVA_OPTS -Djavax.net.debug=ssl:handshake"
	JAVA_OPTS="$JAVA_OPTS -Djavax.net.debug=all"
elif [[ "$@" == *--debug* ]] ; then
	JAVA_OPTS="$JAVA_OPTS -Ddebug.level=DEBUG"
fi
	
java $JAVA_OPTS -cp $root/$jar:$dir org.scriptbox.panopticon.main.MonitorCli "$@"
