#!/bin/bash

jar=panopticon.sa-1.0-SNAPSHOT-standalone-distro.jar
dir=$(dirname $0)
if [[ -f $jar ]] ; then
	root=$dir
else
	root=$dir/../target
fi	

if [[ $(uname) = "Darwin" ]] ; then
	ip=$(/sbin/ifconfig en0 | grep 'inet ' | cut -d' ' -f2)
else 
	ip=$(/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | cut -d' ' -f1)
fi

port=${1:-7800}
jmx_port=$((port + 1))
listen_host=${2:-$ip}

if [[ -n $3 ]] ; then
    DB_ARGS=-Dcassandra.host=$3
fi

set -x
JAVA_OPTS="\
        $DB_ARGS \
        -Dlogback.configurationFile=panopticon-logback.xml \
        -Djetty.hostname=${listen_host} \
        -Djetty.port=${port} \
        -Dcom.sun.management.jmxremote.port=$jmx_port \
    -Dcom.sun.management.jmxremote.ssl=false \
    -Dcom.sun.management.jmxremote.authenticate=false"
java $JAVA_OPTS -cp $dir:$root/$jar org.scriptbox.panopticon.main.MonitorMain "$@"
