#!/bin/bash

jar=horde-1.0-SNAPSHOT-standalone.jar
dir=$(dirname $0)
if [[ -f $jar ]] ; then
	root=$dir
else
	root=$dir/../build/distributions
fi	

if [[ $(uname) = "Darwin" ]] ; then
	ip=$(/sbin/ifconfig en0 | grep 'inet ' | cut -d' ' -f2)
else 
	ip=$(/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | cut -d' ' -f1)
    if [[ -z $ip ]] ; then
        ip=$(/sbin/ifconfig eth0 | grep 'inet ' | awk '{ print $2}')
    fi
fi

# So com.sun virtual machine apis will work
if [[ -f $JAVA_HOME/lib/tools.jar ]] ; then
	echo "Added tools.jar to classpath"
	tools=$JAVA_HOME/lib/tools.jar
fi

CP= 
CP="$CP:$dir"
CP="$CP:$tools"
CP="$CP:$root/$jar"

set -x
JAVA_OPTS="\
        -Dlogback.configurationFile=horde-logback.xml \
    	-Dcom.sun.management.jmxremote.ssl=false \
    	-Dcom.sun.management.jmxremote.authenticate=false"
    	
if [[ "$@" == *--trace* ]] ; then
	JAVA_OPTS="$JAVA_OPTS -Ddebug.level=DEBUG"
	JAVA_OPTS="$JAVA_OPTS -Dtrace.level=DEBUG"
elif [[ "$@" == *--debug* ]] ; then
	JAVA_OPTS="$JAVA_OPTS -Ddebug.level=DEBUG"
fi
    	
java $JAVA_OPTS -cp $CP org.scriptbox.horde.main.HordeMain --address=$ip "$@"
